# Generated by Django 4.0.4 on 2022-05-22 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0002_profilemodel_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduralSheetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakl', models.TextField(verbose_name='Заключение врача специалиста')),
                ('dlii', models.TextField(verbose_name='Данные лабараторно-инструментальных исследований')),
                ('ooe', models.IntegerField(choices=[(0, 'Выраженный'), (1, 'Слабый'), (2, 'Отсутствует')], default=0, verbose_name='Оценка оздоровительного эффекта')),
                ('doz', models.TextField(verbose_name='Диагноз основного заболевания')),
                ('dsz', models.TextField(verbose_name='Диагноз сопутствующих заболеваний')),
                ('sport', models.IntegerField(choices=[(0, 'Разрешены'), (1, 'Ограничены'), (2, 'Не разрешены')], default=0, verbose_name='Спортивные игры')),
                ('excursions', models.IntegerField(choices=[(0, 'Разрешены'), (1, 'Ограничены'), (2, 'Не разрешены')], default=0, verbose_name='Экскурсии')),
                ('kpr', models.TextField(verbose_name='Климатолечение по режиму')),
                ('dr', models.TextField(verbose_name='Климатолечение по режиму')),
                ('diet', models.TextField(verbose_name='Климатолечение по режиму')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Процедурный лист',
                'verbose_name_plural': 'Процедурные листы',
            },
        ),
    ]
