# Generated by Django 4.0.4 on 2022-05-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0004_proceduralsheetmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(choices=[(0, 'Концерты звезд'), (1, 'Общие сборы'), (2, 'Пляжная анимация'), (3, 'Тематические дни'), (4, 'Видеосъемка и постобработка'), (5, 'Художественная фотография, ретушь'), (6, 'Графика, дизайн'), (7, 'Блогинг, основы журналистики'), (8, 'Создание сувениров'), (9, 'Футбол'), (10, 'Шахматы'), (11, 'Волейбол')], default=0, verbose_name='Мероприятие')),
                ('status', models.IntegerField(default=1, verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
