# Generated by Django 4.0.4 on 2022-05-22 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_achievementsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementsmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
