# Generated by Django 4.0.4 on 2022-05-22 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_app', '0003_eventsmodel_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
